name: "Build project and run unit tests"

on:
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug
  VCPKG_ROOT: ${{github.workspace}}/vcpkg

jobs:
  build_linux:
    name: "Linux Build (Debug)"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1  

    - name: Configure vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg && ./bootstrap-vcpkg.sh

    - name: Configure build and install packages
      run: cmake --preset=default

    - name: Build project
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}}

  build_windows:
    name: "Windows Build (Debug)"
    runs-on: windows-latest
    steps:
    - name: Configure vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg && ./bootstrap-vcpkg.sh
