name: "Build project and run unit tests"

on:
  pull_request:
    branches: [ main ]

env:
  VCPKG_ROOT: ${{github.workspace}}/vcpkg

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]

    name: "Linux build (${{ matrix.build_type }})"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Configure vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg && ./bootstrap-vcpkg.sh

    - name: Configure build and install packages
      run: cmake --preset=default

    - name: Build project
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{ matrix.build_type }}
