name: "Build code and run unit tests"

on:
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: "Build source code"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg && ./bootstrap-vcpkg.sh

    - name: Configure the VCPKG_ROOT environment variable
      run: |
        export VCPKG_ROOT=${{github.workspace}}/vcpkg
        export PATH=$VCPKG_ROOT:$PATH

    - name: Configure the build using CMake
      run: cmake --preset=default

    - name: Build the project
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}}
